
#ifndef SPACE_GAME_H
#define SPACE_GAME_H

char 	EepromWriteBlock(struct EepromBlockStruct *block);
char 	EepromReadBlock(u16 blockId,struct EepromBlockStruct *block);
void 	ResumeSong();
void	StopSong();
void	TSPRITE_DIRECT( u8 *data, s16 x, s16 y );
void	TSPRITE( s16 index, s16 x, s16 y );
void	TSPRITE_BLANK( s16 index, s16 x, s16 y );
void	ClearMap(u8 val);
void	ClearMapY(u8 val,u8 y1,u8 y2);
void	ClearSubMap(u8 val);
void	add_score(u16  val);
void	hiscore_save_to_eeprom(u8 *ram);
u8 		how_many_baddies();
void 	ugo(u8 x,u8 y);
void 	uprintc(u8 a);
void 	ucprintx(const char *text);
void 	uprintx(const char *text);
void 	printx_ram(const char *text);
u8 decimal_sub2( char *digit, u16  inval );
u8 decimal_sub3(char *dig,u16  num);
void print_decimal(u16  val,u8 num);
void print_digit(u8 val);
void print_byte(u8 val);
void prdec_small(s16 val);
void print_score(u16  val,u8 num);
void draw_hiscore();
void draw_enter();
void uze_hiscore_enter();
s8	uze_hiscore_getrank(s16 newscore);
int	uze_hiscore_insert(s16 newscore);
void	hiscore_check(s16 newscore);
void uze_hiscore_init();
void	respawn(u8 i);
void	hit_block_vs_baddie();
void	hit_player_vs_baddie();
void	draw_player();
void	draw_baddie(s16 idx);
int		read_map(s16 x,s16 y);
void 	set_map(s16 x,s16 y,u8 a);
void	prnumber(s16 num,s16 x,s16 y);
void	player_walk();
void trigger_stars();
void check_supas();
void	block_move();
void	block_crush();
void	block_remove();
void do_block();
u8	TSPRITE2(s16 index,s16 x,s16 y);
void	draw_block();
void	draw_snoblock();
void	snoblock_crush();
void	draw_supa(u8 index);
void	start_block(s16 type,s16 x,s16 y);
void player_wait_for_block();
void	do_player2();
s8 next_player(s8 i);
void player_die();
void	do_player();
void see_font();
void SelectTileset(u8 setindex);
void	draw_title();
void	draw_background();
void	draw_stars();
void	draw_background_debug();
void	baddie_stun(s16 idx);
void force_stun(u8 idx);
int	check_stun(s16 idx);
void	baddie_move(s16 idx);
void start_snoblock(s16 x,s16 y);
void	do_baddie2(s16 idx);
void do_egg(s16 idx);
void baddie_crush(s16 idx);
void baddie_limbo(s16 idx);
void	do_baddie(s16 idx);
void	start_baddie(s16 idx);
void draw_topwall(u8 ex);
void draw_botwall(u8 ex);
void draw_leftwall(u8 ex);
void draw_rightwall(u8 ex);
void update_panel();
void draw_main();
void	draw_menu_stars();
void PanelClear();
void draw_idle(OBJECT *p);
void move_bullets();
void	fire_bullet();
void	do_idle(OBJECT *p);
void new_level();
void restart_level();
void	draw_soundmenu(OBJECT *p);
void	updown4(OBJECT *p,s16 max);
void	do_soundmenu(OBJECT *p);
void new_game();
void	boot();

#endif
